name: Build and Deploy Docker Image to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        env:
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          echo $ACR_PASSWORD | docker login ${{ secrets.ACR_LOGIN_SERVER }} --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/retrieveuserinfoapi:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/retrieveuserinfoapi:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set --name ${{ secrets.APP_SERVICE_NAME }} --resource-group Vamsi_Dev_Play --docker-custom-image-name ${{ secrets.ACR_LOGIN_SERVER }}/retrieveuserinfoapi:${{ github.sha }}
